version: "3.7"

services:
  api:
    build: .
    ports:
      - 3000
    restart: always
    deploy:
      replicas: 2
    networks:
      - addressapi

  web:
    build:
      context: ./nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on:
      - api
    links:
      - api
    networks:
      - addressapi

networks:
  addressapi:
    driver: bridge