version: "3.7"

services:
  db:
    image: postgres:13.1
    container_name: postgres_container
    restart: always
    command: postgres -c 'max_connections=300' -c 'shared_buffers=1GB'
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-P@ssw0rd}
      PGDATA: /data/addressapi
    volumes:
      - postgres-data:/data/addressapi
    ports:
      - "5432:5432"
    networks:
      - address-api
 
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:4.30
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-P@ssw0rd}
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - "${PGADMIN_PORT:-5050}:5050"
    networks:
      - address-api
    volumes:
      - pgadmin:/root/.pgadmin
    links:
      - "db:postgres_container"

networks:
  address-api:
    driver: bridge

volumes:
  postgres-data:
  pgadmin: