definitions:
  models.Amphure:
    properties:
      code:
        type: string
      id:
        description: gorm.Model
        type: integer
      name_en:
        type: string
      name_th:
        type: string
      province_id:
        type: integer
    type: object
  models.District:
    properties:
      amphure_id:
        type: integer
      id:
        type: integer
      name_en:
        type: string
      name_th:
        type: string
      zip_code:
        type: integer
    type: object
  models.Province:
    properties:
      code:
        type: string
      geography_id:
        type: integer
      id:
        description: gorm.Model
        type: integer
      name_en:
        type: string
      name_th:
        example: Bangkok
        type: string
    type: object
  models.ResponseHTTP:
    properties:
      data:
        type: object
      message:
        type: string
      success:
        type: boolean
    type: object
info:
  contact: {}
paths:
  /api/v1/amphures:
    get:
      consumes:
      - application/json
      description: Get all amphures
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/models.ResponseHTTP'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/models.Amphure'
                  type: array
              type: object
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/models.ResponseHTTP'
      summary: Get all amphures
      tags:
      - amphures
  /api/v1/amphures/province/{province_id}:
    get:
      consumes:
      - application/json
      description: Get all amphures by province_id
      parameters:
      - description: Province ID
        in: path
        name: province_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/models.ResponseHTTP'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/models.Amphure'
                  type: array
              type: object
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ResponseHTTP'
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/models.ResponseHTTP'
      summary: Get all amphures by province_id
      tags:
      - amphures
  /api/v1/districts:
    get:
      consumes:
      - application/json
      description: Get all districts
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/models.ResponseHTTP'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/models.District'
                  type: array
              type: object
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/models.ResponseHTTP'
      summary: Get all districts
      tags:
      - districts
  /api/v1/districts/amphure/{amphure_id}:
    get:
      consumes:
      - application/json
      description: Get all districts by amphure_id
      parameters:
      - description: Amphure ID
        in: path
        name: amphure_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/models.ResponseHTTP'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/models.District'
                  type: array
              type: object
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ResponseHTTP'
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/models.ResponseHTTP'
      summary: Get all districts by amphure_id
      tags:
      - districts
  /api/v1/provinces:
    get:
      consumes:
      - application/json
      description: Get all provinces
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/models.ResponseHTTP'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/models.Province'
                  type: array
              type: object
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/models.ResponseHTTP'
      summary: Get all provinces
      tags:
      - provinces
swagger: "2.0"
